### ISSUE TITLE
make the code a little neater by shortening @liveCodeLabCoreInstance

### ISSUE THREAD

**Issue by davidedc** [davidedc/livecodelab#185]
@liveCodeLabCoreInstance.timeKeeper.resetTime()  if frame is 0
    @liveCodeLabCoreInstance.blendControls.animationStyleUpdateIfChanged()
    @liveCodeLabCoreInstance.backgroundPainter.simpleGradientUpdateIfChanged()
    @liveCodeLabCoreInstance.soundSystem.changeUpdatesPerMinuteIfNeeded()

...maybe those lines can be made prettier as in

    lclInst = @liveCodeLabCoreInstance
    lclInst.timeKeeper.resetTime()  if frame is 0
    lclInst.blendControls.animationStyleUpdateIfChanged()
    lclInst.backgroundPainter.simpleGradientUpdateIfChanged()
    lclInst.soundSystem

**Comment by rumblesan** [comment]
I think this is actually merged in now so we can close it.

as far as using @liveCodeLabCore_three instead of THREE... I don't remember making that change haha. Though my preference would always be to steer clear of global variables and use dependency injection instead. even if we're injecting a global variable, at least the entry point is clear. YMMV though obviously
